/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MrudAmbulanceWlList {
    }
}
declare global {
    interface HTMLMrudAmbulanceWlListElement extends Components.MrudAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLMrudAmbulanceWlListElement: {
        prototype: HTMLMrudAmbulanceWlListElement;
        new (): HTMLMrudAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "mrud-ambulance-wl-list": HTMLMrudAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface MrudAmbulanceWlList {
    }
    interface IntrinsicElements {
        "mrud-ambulance-wl-list": MrudAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mrud-ambulance-wl-list": LocalJSX.MrudAmbulanceWlList & JSXBase.HTMLAttributes<HTMLMrudAmbulanceWlListElement>;
        }
    }
}
